### PR TITLE
Strict mode false open api to ts plugin

### PR DESCRIPTION
**Pull request by furozen**
## What kind of change does this PR introduce?

set strict mode false for openapi-schema-to-json-schema

add example of [openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen)

### CODE REVIEW

**Comment by toomuchdesign** [comment]
Hi @furozen,
thanks for your contribution.

Would you mind explaining the goal of this PR?

**Comment by toomuchdesign** [comment]
`openapi-ts-json-schema` is currently only focusing on generating JSON schemas from OpenAPI. Could you expand on what would be the value of integrating `openapi-typescript` compared to using the same library separately?

As for the issue you mentioned:
```
"id": {
            "type": "integer",
            "format": "int64"
          },
```
...I'd be grateful if you could open an issue with the relevant information.

Thank you!

**Comment by furozen** [comment]
> Could you expand on what would be the value of integrating openapi-typescript compared to using the same library separately?

oh Sir! It is not about what approach is better, it is about ability to develop plugin which working with the source data too.
the open-api plugin is there as example. (it would very  helpfull for me if you describe how avoid add libs for plugin to common package)

>As for the issue you mentioned
about that - I doubt it is issue, because it happens for sources which are not fully standartazied(I guess). 
but ok i'll make the  issue.

**Comment by toomuchdesign** [comment]
I see, so the PR is about defining a new `openApiTSCodegenPlugin` plugin.

I'd suggest to begin with implementing custom plugins in user land (in your codebase) and ensure current `openapi-ts-json-schema` plugin api provides enough surface area to support your use case.

Happy to review/extend plugin api based on real world feedback.

**Comment by furozen** [comment]
> I see, so the PR is about defining a new openApiTSCodegenPlugin plugin.
hmm.. no.
The MR is about:
Снимок экрана 2024-04-12 в 14 54 06
and

Снимок экрана 2024-04-12 в 14 53 01

without these changes I do no use the tool and I can't plugins that I want

**Comment by toomuchdesign** [comment]
I see 10 files changed in the PR diff. Are you sure the committed changes reflect the goal of the PR?

Back to the specific changes mentioned in your last message:
- `fromSchema` strict mode. Just asking: how does it change the output? And why would you need it? Is not mentioned in [openapi-schema-to-json-schema docs](https://github.com/openapi-contrib/openapi-schema-to-json-schema/tree/main?tab=readme-ov-file#options).
- +1 for adding `openApiSchemaPath` to Plugin input

**Comment by toomuchdesign** [comment]
Plugin API was reviewed to access `openapi-ts-json-schema` option object: https://github.com/toomuchdesign/openapi-ts-json-schema/commit/395a61e6a9388ede05595044a2058de7e6210590

**Pull request closed without merging**
